@startuml
skinparam nodesep 80
skinparam ranksep 70
skinparam linetype ortho

skinparam state {
  BackgroundColor LightBlue
  BorderColor Blue
}

state "MenuState\n----\nTheme Song" as MenuState
state "PlayState\n----\nIncreasing\nDIFFICULTY" as PlayState
state "GameOverState\n----\nSave & Score Display\nCRASH Sound Effect" as GameOverState

[*] -down-> MenuState : Open Game

MenuState -down-> PlayState : Space Key
PlayState -down-> GameOverState : CRASH

GameOverState -left-> MenuState : ANY KEY

MenuState -right-> [*] : QUIT \nGame
PlayState -right-> [*] : Quit \nGame
GameOverState -right-> [*] : Quit Game
@enduml